# Site settings
title: Korthaj
name: Stefan Nilsson
email: trolleriprofessorn@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Stefan Nilsson's personal website.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://korthaj.github.io" # the base hostname & protocol for your site

# github_username:  korthaj
# twitter_username: 

# Build settings
markdown: kramdown
